name: mcp-app
services:
  server-mcp:
    build:
      context: .
      dockerfile: ./apps/server-mcp/Dockerfile
    environment:
      MCP_PORT: 8000
    expose:
      - "8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
